#!/usr/bin/perl

use strict;
use warnings;

# Time between iterations of the bot.
# The bot hits public API nodes with periodic polling. let's try to be nice about it.

my $sleep_secs = 30;

#----------------------------------------------------------
# Loops forever calling the betacornbot script
#----------------------------------------------------------

print "botloop starting (forever loop).\n";

while (1) {

    print "=============================================================\n";
    print "calling betdailycoinbot script.\n";
    print "=============================================================\n";
    
    my $status = system("./betdailycoinbot");
    
    my $signal = $status & 0xff;
    my $exit_code = ($status >> 8) & 0xff;

    print "=============================================================\n";
    print "betdailycoinbot returned signal $signal, exit code $exit_code\n";
    print "sleeping...\n";
    print "=============================================================\n";
    
    sleep $sleep_secs;
}
